# Jekyll Defaults
title: blueface
description: A small and simple site I made to test out Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog

url: "http://thien.io/blueface"
github: http://github.com/tnguyen/blueface
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/posts/page:num"
rss_path: /feed.xml
navigation:
- text: Posts
  url: /posts/
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
